### ISSUE TITLE
ubuntu_install.sh & install_zxing.sh missing

### ISSUE THREAD

**Issue by messaoudi-mounir** [devcon14/cmis-capture#1]
Hello,

Can you please push ubuntu_install.sh and install_zxing.sh missing

Thanks advance

**Comment by devcon14** [comment]
Hi,

Thanks for pointing this out.
I have some other changes to add.
So I'll work on merging everything and let you know once the docker dependencies are fixed.

**Comment by devcon14** [comment]
Ok @messaoudi-mounir, I've pushed the files.
The image is also available on docker hub now.
